// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimePlanner.DataAccess;

#nullable disable

namespace TimePlanner.DataAccess.Migrations
{
    [DbContext(typeof(TimePlannerDbContext))]
    [Migration("20220314111838_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TimePlanner.DataAccess.Entities.StatusEntity", b =>
                {
                    b.Property<Guid>("StatusEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StatusID");

                    b.Property<DateTime?>("BreakStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Deposit")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Pause")
                        .HasColumnType("time");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("UndistributedTime")
                        .HasColumnType("time");

                    b.HasKey("StatusEntityId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("TimePlanner.DataAccess.Entities.WorkItemEntity", b =>
                {
                    b.Property<Guid>("WorkItemEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("WorkItemId");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StatusEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WorkItemEntityId");

                    b.HasIndex("StatusEntityId");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("TimePlanner.DataAccess.Entities.WorkItemEntity", b =>
                {
                    b.HasOne("TimePlanner.DataAccess.Entities.StatusEntity", null)
                        .WithMany("WorkItems")
                        .HasForeignKey("StatusEntityId");
                });

            modelBuilder.Entity("TimePlanner.DataAccess.Entities.StatusEntity", b =>
                {
                    b.Navigation("WorkItems");
                });
#pragma warning restore 612, 618
        }
    }
}
